version: '3.8'
services:
  database:
    image: postgres:17.1
    container_name: gestor_academico_container
    restart: always
    environment:
      POSTGRES_USER: ${mi_usuario}
      POSTGRES_PASSWORD: ${hola123}
      POSTGRES_DB: ${gestor_academico}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: nestjs_container
    restart: always
    depends_on:
      - database
    env_file:
      - .docker.env
    ports:
      - "3000:3000"
    command: npm run start:prod

volumes:
  postgres_data:


